syntax on
set autochdir
filetype plugin indent on
try
    colorscheme Monokai
catch
    silent! colorscheme desert
endtry
if has('gui_running')
  set guifont=Consolas:h9:cANSI
  " Remove the toolbars and other things from the GUI
  set guioptions-=m
  set guioptions-=T
  set guioptions-=r
endif
if has('syntax') && has('eval')
  packadd! matchit
endif
set shiftwidth=4
set softtabstop=4
set expandtab
set nobackup
set nowritebackup
set noswapfile
set number
set relativenumber

set wildmenu
set wildoptions=pum
set whichwrap=b,s,<,>,h,l,[,]

" Using filetype plugin indent instead for workflowish
" Set smartindent
nnoremap Y y$
nnoremap ; :
nnoremap : ;
" Exit quickly
inoremap kj <ESC>

" Better window mapping
nnoremap <C-l> <C-w>v<C-w><C-l>
nnoremap <C-j> <C-w>s<C-w><C-j>
nnoremap <C-q> :q<CR>
nnoremap <C-x> :x<CR>
nnoremap <C-e> :q!<CR>
nnoremap <C-s> :%s//g<Left><Left>

" Wrap
:map \p wbi(<Esc>ea)<Esc>
:map \c wbi{<Esc>ea}<Esc>

" Do not show stupid q: window
" map q: :q
" Force usage of <C-commands>
nmap ;q <CR>
nmap ;x <CR>

fun! ToggleNumber() abort "{{{
    if exists('+relativenumber')
    	:exec "setl nu!"
        :exec "setl rnu!"
    else
        setl nu! 
    endif
endf "}}}
nnoremap <C-n> :call ToggleNumber()<CR>

" Easy pasting
set pastetoggle=<F10>
inoremap <C-v> <F10><C-r>+<F10>

" Persistent undo
if has('persistent_undo')
  set undofile
  set undodir=~/.vim/undodir
endif

cmap <C-w> w !sudo tee > /dev/null %<CR>
cmap <C-v> e $MYVIMRC<CR>

